name: abus
description: >
  ABUS (A-synchronous Business Unified System) is a unified approach to handling asynchronous operations and API interactions with built-in optimistic updates, rollback capabilities, and error handling.
version: 0.0.7
homepage: https://github.com/Bum-Ho12/abus
repository: https://github.com/Bum-Ho12/abus
issue_tracker: https://github.com/Bum-Ho12/abus/issues

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_bloc: ^9.1.1

flutter:
